# Generated by Django 5.2.5 on 2025-08-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('position', models.CharField(max_length=100, verbose_name='Cargo')),
                ('role', models.CharField(choices=[('owner', 'Dueño'), ('intern', 'Becario')], max_length=10, verbose_name='Rol')),
                ('bio', models.TextField(verbose_name='Biografía')),
                ('expertise', models.TextField(verbose_name='Especialidades')),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='Foto')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('order', models.IntegerField(default=0, verbose_name='Orden de aparición')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Miembro del equipo',
                'verbose_name_plural': 'Miembros del equipo',
                'ordering': ['order', 'name'],
            },
        ),
    ]
